### ISSUE TITLE
inline CSS styles

### ISSUE THREAD

**Issue by berryny** [HiAugust/onepager#3]
Move inline style to the external css file
```
<h1 style="font-family: Helvetica; font-size: 64px; font-color ffffff; ">WEB DEVELOPMENT</h1>
```

**Comment by HiAugust** [comment]
done, in html   <h1 id="About">WEB DEVELOPMENT</h1>
in css:
h1#About {
	font-family: Helvetica: Arial: sans-serif;
	font-size: 64px; 
	color: #ffffff; 
	text-align: center;
}
