### ISSUE TITLE
HTML Code

### ISSUE THREAD

**Issue by berryny** [HiAugust/onepager#4]
Fix html and include the right content markup
```
<div>
		<h2>BLOG</h2>
	</div>

	<div>
		<img src="img/img-programers.jpg" alt="img-programers" width="500" height="300">

	</div>
```

**Comment by HiAugust** [comment]
<h2 class="hdrBlg" id="Blog">BLOG</h2>
		</div>

		<div>
			<img src="img/img-programers.jpg" alt="img-programers"
			style="width: 670px;height: 335px;float: left;margin-right: 25px;margin-bottom: 54px">
